### ISSUE TITLE
Fix toobar disappearing when rotating through "more"

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#19]
## I'm submitting a ...  
[x] bug report => search github for a similar issue before submitting  

## ...about   
[x] edit experience / UI  

## Current behavior 
See this video: https://www.screencast.com/t/e15Ij22TajoV

## Expected behavior 
Toolbar shouldn't go away while rotating modes.

**Comment by tvatavuk** [comment]
I seen this issue before, but now I can not reproduce it.

**Comment by tvatavuk** [comment]
Solution is more workaround than real fix. Had to duplicate some CSS rules in JavaScript, to override them. It looks that issue is related to Chrome. Browser sometime emits mouseleave event after click without obvious reason, and this trigger CSS rules to hide toolbar. It was luck that mouseEvent.screenX=0 and  mouseEvent.screenY=0 in case of this fake mouseleave event, so I could compensate in that case. Also didn't find relation between this problem and usage of Shake functionality.
