### ISSUE TITLE
Paste image from clipboard - 4h

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#24]

**Comment by iJungleboy** [comment]
More work would be needed for

1. jpg - ca. 4h - don't do for now
1. better renaming in Edge - 0.5h, if not, 2-4h - try the quick solution, otherwise don't do

**Comment by tvatavuk** [comment]
image past is working for tiny and adam but still have work to finish, fix some issues, clean some code, etc... cca 2h.

**Comment by tvatavuk** [comment]
still not closed because have to remove jquery dependency from paste.js and planning to do it tomorrow

**Comment by tvatavuk** [comment]
* Chrome and Firefox are working without issues (except #32 with paste alert https://github.com/2sic/2sxc-inpage/issues/32)
* Better renaming in Edge is done, but have one more issue related to Edge pasting in TinyMCE that will document separately,
* IE currently can not test because I got error with Promise while opening edit

**Comment by iJungleboy** [comment]
thx. Not uploaded yet, right? I just pushed another small feature.

**Comment by tvatavuk** [comment]
It should be on github.
I'm working in branch **feature/paste-image-from-clipboard**.
That feature branch was published to github, but not merged to develop branch because of two reasons:
- would like first to close issue https://github.com/2sic/2sxc-inpage/issues/25 without new javascript events needed for paste image because it will be simpler to solve it with less js events
- some config for this option, eventually 

Also, I just rebased checkins from develop branch to this feature branch to get there all updates from develop, and than synced to github in this feature branch.

I'm checking is it all ok after rebase. Paste is working. I see that I'm missing some updates in dist but that should probably be solved with running gulp tasks or webpack.

**Comment by iJungleboy** [comment]
core features Config is ready - see #35 and as I can see, #25 is done. Can we close this task?
