### ISSUE TITLE
ensure that paste image keeps cursor position

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#44]
## I'm submitting a ...  
[x] bug report => search github for a similar issue before submitting  

## ...about   
[x] edit experience / UI  

## Steps to implement
* [x] check what is necessary - probably remember cursor position before js-open
* [x] discuss w/Daniel
* [x] implement

**Comment by tvatavuk** [comment]
Removed code that was taking care of focus, and ensured that paste event is propagated to tinymce. It is working in Chrome, FF and Edge as  expected. Paste image is not working in IE (not related to this fix). Also it is possible that sometimes after image paste, tinymce pops blue dialog with text message related to paste. Tinymce code related to that dialog was time bounded. Still didn't see that blue dialogue in local dev installation during testing this last fix so that was looking good.
