### ISSUE TITLE
Review issue 1576

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc-inpage#61]
https://github.com/2sic/2sxc/issues/1576

## Steps to implement
* [x] discuss with 2dm before you start
* [x] research cause, suggest solution
* [x] discuss
* [x] implement

**Comment by tvatavuk** [comment]
Have problem in testing with debounce and ajax, and inpage toolbars where missing after ajax response :-(
Problem solved without debounce but using MutationObserver instead of DOMSubtreeModified event listener.
Last version of 2sxc have some other problems during change of app, so I could not test that part.

**Comment by iJungleboy** [comment]
let's telco...
